[package]
name = "afraid_of_dark"
version = "0.1.0"
edition = "2021"

[features]
default = ["opengl"]
opengl = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assets = { path = "src/engine/assets" }
rustc-serialize = "0.3" # needed by glm @todo! remove glm and use custom math lib or a maintained one
bevy_ecs = ">= 0.16.1"
gl = ">= 0.14.0"
glfw = ">= 0.59.0"
glm = ">= 0.2.3"
image = ">= 0.25.6"
term = ">= 1.0.2"
rand = ">= 0.9.1"
bit-set = "0.8.0"
