[package]
name = "afraid_of_dark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.12.1"
gl = "0.14.0"
glfw = "0.54.0"
term = "0.7.0"
